import type {Computer} from "./ComputerStore.ts";
import { GameController, Briefcase, Code, Robot, FileText, PaintBrush, VideoCamera } from 'phosphor-react';

export const mockComputers: Computer[] = [
    {
        id: '1',
        name: '게이밍 최강 RTX 4090',
        category: 'gaming',
        specs: {
            cpu: 'Intel i9-13900K',
            gpu: 'RTX 4090 24GB',
            ram: '64GB DDR5',
            storage: '2TB NVMe SSD',
        },
        prices: {
            day: 300000,
            week: 1800000,
            month: 8000000,
        },
        image: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800',
        rating: 4.9,
        reviews: 328,
        available: true,
        tags: ['게이밍', '고사양', '4K', 'VR'],
    },
    {
        id: '2',
        name: '영상편집 워크스테이션',
        category: 'workstation',
        specs: {
            cpu: 'AMD Ryzen 9 7950X',
            gpu: 'RTX 4080 16GB',
            ram: '128GB DDR5',
            storage: '4TB NVMe SSD',
        },
        prices: {
            day: 280000,
            week: 1700000,
            month: 7000000,
        },
        image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800',
        rating: 4.8,
        reviews: 156,
        available: true,
        tags: ['영상편집', '4K편집', '프리미어', '다빈치'],
    },
    {
        id: '3',
        name: '코딩 개발용 맥북 프로',
        category: 'development',
        specs: {
            cpu: 'Apple M3 Max',
            gpu: '40-Core GPU',
            ram: '96GB',
            storage: '2TB SSD',
        },
        prices: {
            day: 450000,
            week: 2800000,
            month: 12000000,
        },
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
        rating: 5.0,
        reviews: 89,
        available: true,
        tags: ['개발', 'macOS', 'Xcode', 'iOS'],
    },
    {
        id: '4',
        name: 'AI/ML 딥러닝 서버',
        category: 'ai',
        specs: {
            cpu: 'AMD Threadripper PRO',
            gpu: 'RTX 4090 x2 (SLI)',
            ram: '256GB DDR5',
            storage: '8TB NVMe RAID',
        },
        prices: {
            day: 400000,
            week: 2400000,
            month: 1200000,
        },
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
        rating: 4.9,
        reviews: 45,
        available: true,
        tags: ['AI', '딥러닝', 'CUDA', 'TensorFlow'],
    },
    {
        id: '5',
        name: '가성비 사무용 PC',
        category: 'office',
        specs: {
            cpu: 'Intel i5-13400',
            gpu: 'Intel UHD 730',
            ram: '16GB DDR4',
            storage: '512GB SSD',
        },
        prices: {
            day: 80000,
            week: 500000,
            month: 2000000,
        },
        image: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800',
        rating: 4.5,
        reviews: 234,
        available: true,
        tags: ['사무', '문서작업', '인터넷', '저렴'],
    },
    {
        id: '6',
        name: '3D 모델링 전문가용',
        category: 'design',
        specs: {
            cpu: 'Intel i9-13900KS',
            gpu: 'RTX 4080 Super',
            ram: '64GB DDR5',
            storage: '2TB + 4TB HDD',
        },
        prices: {
            day: 350000,
            week: 2100000,
            month: 9000000,
        },
        image: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=800',
        rating: 4.7,
        reviews: 112,
        available: false,
        tags: ['3D', 'Blender', 'Maya', 'CAD'],
    },
    {
        id: '7',
        name: '스트리밍 방송 세트',
        category: 'streaming',
        specs: {
            cpu: 'Intel i7-13700K',
            gpu: 'RTX 4070 Ti',
            ram: '32GB DDR5',
            storage: '1TB NVMe SSD',
        },
        prices: {
            day: 200000,
            week: 1200000,
            month: 5000000,
        },
        image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800',
        rating: 4.8,
        reviews: 267,
        available: true,
        tags: ['방송', 'OBS', '스트리밍', '트위치'],
    },
    {
        id: '8',
        name: '포토샵 전문가용',
        category: 'design',
        specs: {
            cpu: 'AMD Ryzen 9 7900X',
            gpu: 'RTX 4060 Ti',
            ram: '64GB DDR5',
            storage: '2TB SSD',
        },
        prices: {
            day: 200000,
            week: 1200000,
            month: 5500000,
        },
        image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800',
        rating: 4.6,
        reviews: 178,
        available: true,
        tags: ['포토샵', '디자인', '그래픽', 'Adobe'],
    },
];

export const categories = [
    { id: 'gaming', name: '게이밍', Icon: GameController },
    { id: 'workstation', name: '워크스테이션', Icon: Briefcase },
    { id: 'development', name: '개발', Icon: Code },
    { id: 'ai', name: 'AI/ML', Icon: Robot },
    { id: 'office', name: '사무용', Icon: FileText },
    { id: 'design', name: '디자인', Icon: PaintBrush },
    { id: 'streaming', name: '스트리밍', Icon: VideoCamera },
];